pipeline {
  agent {
    label "SlaveNode1"
  }
  stages {
    stage('Back-end-docker') {
      steps {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
    }
	stage('Back-end-maven') {
      steps {
        sh 'mvn --version'
      }
    }
	stage('Front-end-docker') {
      steps {
        docker { image 'node:16-alpine'  }
      }
    }
    stage('Front-end-node') {
      steps {
        sh 'node --version'
      }
    }
  }
}
