pipeline {
  agent {
    label "SlaveNode1"
  }
  stages {
    stage('Back-end') {
      agent {
        export PATH="$PATH:/usr/bin/docker"
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
